[core]
reloadable = true
order = 0

[package]
version = "0.1.3"
category = "Simulation"
title = "Isaac Sim Demos"
description = "Demos extensions for Isaac Sim"
authors = ["NVIDIA"]
repository = ""
keywords = ["isaac", "demo"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.utils" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}
"omni.kit.commands" = {}
"omni.kit.menu.utils" = {}
"omni.usd" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.motion_planning" = {}
"omni.physx" = {}
"omni.isaac.motion_generation" = {}
"omni.isaac.surface_gripper" = {}
"omni.kit.window.viewport" = {}
"omni.debugdraw" = {}

[[python.module]]
name = "omni.isaac.demos.franka_leonardo"

[[python.module]]
name = "omni.isaac.demos.ur10_preview"

[[python.module]]
name = "omni.isaac.demos.navigation_preview"

[[python.module]]
name = "omni.isaac.demos.sk_building"

[[python.module]]
name = "omni.isaac.demos.ridgeback_navigation"

[[python.module]]
name = "omni.isaac.demos.ridgeback_iiwa_navigation"

[[python.module]]
name = "omni.isaac.demos.tests"
